kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  image: {{ image }}
  ingresses:
    - {{ INGRESS }}
  env:
    - name: BILAG_ENDPOINTS_BREVSERVER_URL
      value: {{ BILAG_ENDPOINTS_BREVSERVER_URL }}
    - name: BILAG_ENDPOINTS_BREVSERVER_SCOPE
      value: {{ BILAG_ENDPOINTS_BREVSERVER_SCOPE }}
    - name: BILAG_BASE_URL
      value: {{ BILAG_BASE_URL }}
    - name: BILAG_AZURE_SCOPE
      value: {{ BILAG_AZURE_SCOPE }}
  liveness:
    path: /actuator/health/liveness
    initialDelay: 20
    failureThreshold: 10
  readiness:
    path: /actuator/health/readiness
    initialDelay: 20
    timeout: 3
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
        groups:
          {{#each REGNSKAP_AD_GROUP_OBJECT_IDS}}
          - id: {{ id }}
          {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: ida
          namespace: traktor
          cluster: prod-fss
  webproxy: true
  vault:
    enabled: true
    paths:
      - kvPath: {{ APPDYNAMICS }}
        mountPath: /var/run/secrets/nais.io/appdynamics
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      memory: 1024Mi