name: Build, deploy dev, draft main

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    permissions:
      contents: write
      packages: write
      pull-requests: write
      id-token: write
    uses: navikt/dok-workflows/.github/workflows/build-deploy-main-gar.yml@main
    secrets: inherit
    with:
      java-version: '21'