name: Dependabot fetch metadata
on:
  pull_request:

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  determine-semver-version:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    outputs:
      update-type: ${{ steps.metadata.outputs.update-type }}
    steps:
      - run: echo 'github.actor=${{ github.actor }}, github.event=${{ github.event }}, github.head_ref=${{ github.head_ref }}, github.event.pull_request.user.login=${{ github.event.pull_request.user.login }}'
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      # The following properties are now available:
      #  - steps.metadata.outputs.dependency-names
      #  - steps.metadata.outputs.dependency-type
      #  - steps.metadata.outputs.update-type

  handle-major-version:
    needs: determine-semver-version
    permissions:
      contents: read
      id-token: write
    if: github.actor == 'dependabot[bot]' && needs.determine-semver-version.outputs.update-type == 'version-update:semver-major'
    uses: navikt/dok-workflows/.github/workflows/build-app-gar.yml@main
    secrets: inherit

  handle-minor-or-patch-version:
    needs: determine-semver-version
    permissions:
      contents: read
      packages: write
      id-token: write
    if: github.actor == 'dependabot[bot]' && needs.determine-semver-version.outputs.update-type != 'version-update:semver-major'
    uses: navikt/dok-workflows/.github/workflows/build-deploy-feature-gar-with-dependabot.yml@main
    secrets: inherit

  merge-branch:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}